### PR TITLE
build(recipe): update to si-prefix==1.3.3

### PR DESCRIPTION
**Pull request by cfobel**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Update the build to use si-prefix version 1.3.3.

### CODE REVIEW

**Comment by cfobel** [comment]
@conda-forge-admin, please rerender

**Comment by cfobel** [comment]
FYI, failing checks seem to be related to conda-forge/status#181

**Comment by cfobel** [comment]
@conda-forge-admin, please rerender

**Comment by cfobel** [comment]
@cjw85, note that the system-wide Azure build issues have now been resolved and all checks are now passing ✔️

**Comment by cjw85** [comment]
Wow. This is a blast from the past. I barely recollect what this is.

Is there a conda-forge process for having someone take ownership of this?

**Review by cjw85 — APPROVED** [review]
LGTM!

**Comment by cfobel** [comment]
> Wow. This is a blast from the past. I barely recollect what this is.

Hahaha. Yeah, once in a while I get someone pinging me with a PR for this project :)

> Is there a conda-forge process for having someone take ownership of this?

I am going to try to follow the instructions from here to add myself as a maintainer: https://conda-forge.org/docs/maintainer/updating_pkgs/#updating-the-maintainer-list

**Comment by cfobel** [comment]
@conda-forge-admin, please add user @cfobel

**Pull request merged**
